version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/opt/project
    environment:
      - PR_LISTING_GITHUB_ORG=great_org
      - PR_LISTING_AUTHOR=author1 author2
      - PR_LISTING_BASIC_AUTH_CREDENTIALS=username:token_auth
